<!-- BEGIN HEAD INCLUDE -->
<meta name="robots" content="noindex,nofollow" />
<!-- Include JQuery -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
<!-- Include Main CSS-->
<link href="/styles.css" media="screen" rel="stylesheet" type="text/css" />
<!-- Include EM CSS -->
<link href="/eventManager/styles.css" rel="stylesheet" type="text/css" />
<!-- Include Colorbox (lightbox) files-->
<link rel="stylesheet" href="/colorbox.css" />
<script src="/assets/jquery.colorbox.js"></script>
<!-- Include Form Validation files --> 
<script type="text/javascript" src="/assets/jquery.validate.js"></script>
<!-- Include JQuery Tooltips -->
<link type="text/css" rel="stylesheet" href="/assets/jquery.qtip.css" />
<script type="text/javascript" src="/assets/jquery.qtip.js"></script>
<!-- Include Google Webfont -->
<link href='http://fonts.googleapis.com/css?family=Josefin+Sans:400,600,700' rel='stylesheet' type='text/css'>
		
<!-- Ready Function for Colorbox and Tooltips -->
	<script>
			$(document).ready(function(){
				$('a[title]').qtip();
				$(".group1").colorbox({rel:'group1', rel:'nofollow'});	
				$(".group2").colorbox({rel:'group2', rel:'nofollow'});	
				$(".group3").colorbox({rel:'group3', rel:'nofollow'});	
				$(".inline").colorbox({inline:true, width:"400px;"});
				$(".youtube").colorbox({iframe:true, innerWidth:750, innerHeight:470});		
			});
	</script> 
	
	<!-- Jot Form-->
	<script src="http://max.jotfor.ms/min/g=feedback2" type="text/javascript">
					  new JotformFeedback({
					     formId		: "22483883263965",
					     buttonText	: "Marketing Manager Feedback",
					     base		: "http://jotformpro.com/",
					     background	: "#86dbed",
					     fontColor	: "#000000",
					     buttonSide	: "left",
					     buttonAlign	: "center",
					     type		: 2,
					     width		: 700,
					     height		: 500
					  });
</script>
<script src="http://max.jotfor.ms/min/g=feedback2" type="text/javascript">
						new JotformFeedback({
						formId:'22483883263965',
						base:'http://jotformpro.com/',
						windowTitle:'Marketing Manager Feedback',
						background:'#86DBED',
						fontColor:'#000000',
						type:2,
						height:500,
						width:700
						});
</script>
<script src="http://max.jotfor.ms/min/g=feedback2" type="text/javascript">
					new JotformFeedback({
					formId:'22484315193958',
					base:'http://jotformpro.com/',
					windowTitle:'Stories from the Schools',
					background:'#86dbed',
					fontColor:'#000',
					type:2,
					height:500,
					width:700
					});
</script>

<link type="text/css" href="/inc/jquery.foobar.2.1.css" rel="Stylesheet" />
<script type="text/javascript" src="/inc/jquery.foobar.2.1.min.js"></script>


<!-- Start FooBar -->
<!--<script type="text/javascript">
  $(function(){
    $foobar({
      "position" : {
        "bar" : "top"
      },
      "cookie" :{
	    	"enabled" : "true"  
      },
      "display" : {
        "type" : "delayed",
        "delay" : 1000,
        "backgroundColor": "#9b53c3",
        "shadow": true,
        "theme": {
	        "bar": "x-white"
	        }
      },
      "messages": [ 
        "The newest version of the Roadmaster Catalog is now available for download. <a href=/downloads/rm/rm-catalog.pdf>Click here to download!</a>",
      ],
    });
  });
</script>-->

<!-- END FooBar -->
